// GENERATED by scripts/dc-to-jsx.mjs. Load order matches Raw Draft.dc.html.
export async function loadEngines(after = {}) {
  await import("./rd-data.js");
  if (after["rd-data.js"]) after["rd-data.js"]();
  await import("./rd-backlog.js");
  if (after["rd-backlog.js"]) after["rd-backlog.js"]();
  await import("./rd-sprint-formats.js");
  if (after["rd-sprint-formats.js"]) after["rd-sprint-formats.js"]();
  await import("./rd-network.js");
  if (after["rd-network.js"]) after["rd-network.js"]();
  await import("./rd-builder.js");
  if (after["rd-builder.js"]) after["rd-builder.js"]();
  await import("./rd-lib.js");
  if (after["rd-lib.js"]) after["rd-lib.js"]();
  await import("./rd-cycle.js");
  if (after["rd-cycle.js"]) after["rd-cycle.js"]();
  await import("./rd-cycle-scroll.js");
  if (after["rd-cycle-scroll.js"]) after["rd-cycle-scroll.js"]();
  await import("./rd-uptime.js");
  if (after["rd-uptime.js"]) after["rd-uptime.js"]();
  await import("./rd-ascii.js");
  if (after["rd-ascii.js"]) after["rd-ascii.js"]();
  await import("./rd-structure.js");
  if (after["rd-structure.js"]) after["rd-structure.js"]();
  await import("./rd-visual.js");
  if (after["rd-visual.js"]) after["rd-visual.js"]();
}
